// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppSnapshot: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("get_app_snapshot")),
	startSession: (streamUrl: string) => typedError<AppSnapshot, string>(__TAURI_INVOKE("start_session", { streamUrl })),
	stopSession: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("stop_session")),
	updateSettings: (settings: AppSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("update_settings", { settings })),
	showWindow: (label: string) => typedError<null, string>(__TAURI_INVOKE("show_window", { label })),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	connectFeed: (feed: Channel<AppFeed>) => __TAURI_INVOKE<void>("connect_feed", { feed }),
	getRecentLogs: (afterId: number | null) => __TAURI_INVOKE<DeveloperLogEntry[]>("get_recent_logs", { afterId }),
	getToolStatuses: () => __TAURI_INVOKE<ToolStatus[]>("get_tool_statuses"),
	getModelCatalog: () => typedError<ModelInfo[], string>(__TAURI_INVOKE("get_model_catalog")),
	installModel: (modelId: string) => typedError<ModelInfo, string>(__TAURI_INVOKE("install_model", { modelId })),
	uninstallModel: (modelId: string) => typedError<ModelInfo, string>(__TAURI_INVOKE("uninstall_model", { modelId })),
	setCoreMlEnabled: (modelId: string, enabled: boolean) => typedError<ModelInfo, string>(__TAURI_INVOKE("set_core_ml_enabled", { modelId, enabled })),
	cancelModelDownload: () => typedError<null, string>(__TAURI_INVOKE("cancel_model_download")),
	hideWindow: (label: string) => typedError<null, string>(__TAURI_INVOKE("hide_window", { label })),
	systemYtDlpAvailable: () => __TAURI_INVOKE<boolean>("system_yt_dlp_available"),
	/**
	 *  Returns the latest published yt-dlp version when it differs from what's
	 *  currently resolved, or `None` when already current.
	 */
	checkYtDlpUpdate: () => typedError<string | null, string>(__TAURI_INVOKE("check_yt_dlp_update")),
	installYtDlp: () => typedError<ToolStatus, string>(__TAURI_INVOKE("install_yt_dlp")),
	cancelToolDownload: () => typedError<null, string>(__TAURI_INVOKE("cancel_tool_download")),
	/**
	 *  Deletes all downloaded models and managed yt-dlp, resets settings to
	 *  defaults, and opens the onboarding window so the user can start fresh.
	 */
	resetApp: () => typedError<null, string>(__TAURI_INVOKE("reset_app")),
};

/** Events */
export const events = {
	diagnosticsEvent: makeEvent<DiagnosticsEvent>("diagnostics-event"),
	metricsEvent: makeEvent<MetricsEvent>("metrics-event"),
	modelDownloadEvent: makeEvent<ModelDownloadEvent>("model-download-event"),
	sessionErrorEvent: makeEvent<SessionErrorEvent>("session-error-event"),
	sessionStateEvent: makeEvent<SessionStateEvent>("session-state-event"),
	settingsUpdatedEvent: makeEvent<SettingsUpdatedEvent>("settings-updated-event"),
	subtitleClearEvent: makeEvent<SubtitleClearEvent>("subtitle-clear-event"),
	subtitleEvent: makeEvent<SubtitleEvent>("subtitle-event"),
	subtitlePartialEvent: makeEvent<SubtitlePartialEvent>("subtitle-partial-event"),
};

/* Types */
/**
 *  Messages pushed to the bar over a persistent [`Channel`] it registers at
 *  startup — same IPC path as commands, so delivery to the (transparent) bar
 *  window is reliable where broadcast events were not.
 * 
 *  No `rename_all`: specta doesn't apply it to tagged-enum variant fields, so
 *  both sides stay `snake_case` to avoid a type/runtime mismatch.
 */
export type AppFeed = { type: "State"; state: SessionStatus } | { type: "Subtitle"; start_ms: number; end_ms: number; text: string } | { type: "Partial"; stable_text: string; unstable_text: string } | { type: "Clear" } | { type: "Error"; message: string } | { type: "Settings"; settings: AppSettings };

/**
 *  All persisted user settings, kept as one flat struct so the JSON and the
 *  generated TypeScript binding stay simple. Fields are grouped by concern below.
 * 
 *  `#[serde(default)]`: settings from an older version missing newer fields
 *  fall back to defaults instead of failing to load.
 */
export type AppSettings = {
	model?: string,
	modelPath?: string,
	inferenceBackend?: string,
	sourceLanguage?: string,
	task?: string,
	/**
	 *  "stable" waits for final utterance boundaries before rendering
	 *  translation; "live" also renders rolling partials for lower latency.
	 */
	captionMode?: string,
	chunkMode?: string,
	/**
	 *  Silero probability preset: "high" detects quieter speech, "strict"
	 *  rejects more music/noise, and "balanced" is the general default.
	 */
	vadSensitivity?: string,
	minimumChunkMs?: number,
	maximumChunkMs?: number,
	endSilenceMs?: number,
	overlapMs?: number,
	subtitleOffsetMs?: number,
	fontSizePx?: number,
	fontWeight?: number,
	fontFamily?: string,
	textColor?: string,
	backgroundColor?: string,
	backgroundOpacity?: number,
	alwaysOnTop?: boolean,
	clickThrough?: boolean,
	cookieMode?: string,
	browser?: string,
	browserProfile?: string,
	cookieFile?: string,
	automaticToolUpdates?: boolean,
	/**
	 *  Whether yt-dlp is resolved from `PATH` ("system") or downloaded and
	 *  self-updated by `Kaigai` ("managed"). ffmpeg has no such choice: it
	 *  ships bundled with the app and is never resolved at runtime.
	 */
	ytDlpSource?: string,
	/**
	 *  "bundled" (default) points yt-dlp at Kaigai's `QuickJS` sidecar for
	 *  `YouTube`'s JS challenges; "system" leaves it to find its own runtime
	 *  on `PATH` (yt-dlp only tries Deno by default).
	 */
	jsRuntimeSource?: string,
	// Whether the first-run setup tour has been completed.
	onboarded?: boolean,
};

export type AppSnapshot = {
	sessionState: SessionStatus,
	streamUrl: string | null,
	settings: AppSettings,
};

export type DeveloperLogEntry = {
	id: number,
	message: string,
};

export type DiagnosticsEvent = {
	message: string,
};

export type MetricsEvent = {
	audioMs: number,
	chunkMs: number,
	inferenceMs: number | null,
	realtimeFactor: number | null,
	reason: string,
	queueDepth: number,
	queueDelayMs: number,
	pcmGapMs: number,
	captureLagMs: number,
};

export type ModelDownloadEvent = {
	modelId: string,
	state: string,
	downloadedBytes: number,
	totalBytes: number,
	bytesPerSecond: number,
	etaSeconds: number | null,
	error: string | null,
};

export type ModelInfo = {
	id: string,
	label: string,
	provider: string,
	description: string,
	fileName: string,
	sizeBytes: number,
	installed: boolean,
	active: boolean,
	supportsTranslate: boolean,
	coreMlAvailable: boolean,
	coreMlInstalled: boolean,
	coreMlEnabled: boolean,
	coreMlSizeBytes: number | null,
};

export type SessionErrorEvent = {
	message: string,
};

export type SessionStateEvent = {
	state: SessionStatus,
};

export type SessionStatus = "idle" | "starting" | "loading" | "buffering" | "running" | "reconnecting" | "stopping" | "failed";

export type SettingsUpdatedEvent = {
	settings: AppSettings,
};

export type SubtitleClearEvent = null;

export type SubtitleEvent = {
	startMs: number,
	endMs: number,
	text: string,
	inferenceMs: number,
};

export type SubtitlePartialEvent = {
	stableText: string,
	unstableText: string,
	revision: number,
};

export type Tool = "yt-dlp" | "ffmpeg" | "quick-js";

export type ToolSource = "managed" | "bundled" | "path" | "missing";

export type ToolStatus = {
	tool: Tool,
	source: ToolSource,
	path: string | null,
	version: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

